export const PRM_STORAGE_KEYS = Object.freeze({
  PERSONAS: "prm_personas",
  ACTIVE_PERSONA_ID: "prm_active_persona_id",
  VIEW_MODE: "prm_view_mode",
  LAST_ACTIVE_TAB: "prm_last_active_tab"
});

export const PRM_VIEW_MODES = Object.freeze({
  SINGLE: "single",
  SPLIT: "split",
  SPLIT_THREE: "split_three",
  SPLIT_FOUR: "split_four"
});

export const PRM_MESSAGE_TYPES = Object.freeze({
  GET_STATE: "PRM_GET_STATE",
  SAVE_PERSONA: "PRM_SAVE_PERSONA",
  DELETE_PERSONA: "PRM_DELETE_PERSONA",
  SET_ACTIVE_PERSONA: "PRM_SET_ACTIVE_PERSONA",
  SET_VIEW_MODE: "PRM_SET_VIEW_MODE",
  GET_PERSONA_FIELD_METADATA: "PRM_GET_PERSONA_FIELD_METADATA",
  GET_ACTIVE_PERSONA: "PRM_GET_ACTIVE_PERSONA",
  GET_SIMULATION_CONTEXT: "PRM_GET_SIMULATION_CONTEXT",
  ACTIVE_PERSONA_CHANGED: "PRM_ACTIVE_PERSONA_CHANGED",
  SPLIT_SCREEN_REQUESTED: "PRM_SPLIT_SCREEN_REQUESTED",
  SINGLE_VIEW_REQUESTED: "PRM_SINGLE_VIEW_REQUESTED"
});
